server:
  port: 8080
  servlet:
    context-path: /timeline

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.77.176.55:3306/timeline?useUnicode=true&characterEncoding=utf8
    username: root
    password: root

# 附件存放地址
file:
  upload-dir: ./uploads